// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    InputNumber: typeof import('./src/components/InputNumber.vue')['default'];
    NInput: typeof import('naive-ui')['NInput'];
    NInputNumber: typeof import('naive-ui')['NInputNumber'];
    NTable: typeof import('naive-ui')['NTable'];
    NumberInput: typeof import('./src/components/NumberInput.vue')['default'];
    QAvatar: typeof import('quasar')['QAvatar'];
    QBtn: typeof import('quasar')['QBtn'];
    QDrawer: typeof import('quasar')['QDrawer'];
    QHeader: typeof import('quasar')['QHeader'];
    QLayout: typeof import('quasar')['QLayout'];
    QPageContainer: typeof import('quasar')['QPageContainer'];
    QToolbar: typeof import('quasar')['QToolbar'];
    QToolbarTitle: typeof import('quasar')['QToolbarTitle'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    Starport: typeof import('vue-starport')['Starport'];
    StarportCarrier: typeof import('vue-starport')['StarportCarrier'];
    VApp: typeof import('vuetify/components')['VApp'];
    VAppBar: typeof import('vuetify/components')['VAppBar'];
    VAppBarNavIcon: typeof import('vuetify/components')['VAppBarNavIcon'];
    VBtn: typeof import('vuetify/components')['VBtn'];
    VCard: typeof import('vuetify/components')['VCard'];
    VMain: typeof import('vuetify/components')['VMain'];
    VNavigationDrawer: typeof import('vuetify/components')['VNavigationDrawer'];
    VTextField: typeof import('vuetify/components')['VTextField'];
    VToolbarTitle: typeof import('vuetify/components')['VToolbarTitle'];
  }
}
