// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default'];
    DemoCanvas: typeof import('./src/components/DemoCanvas.vue')['default'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    Footer: typeof import('./src/components/Footer.vue')['default'];
    NInput: typeof import('naive-ui')['NInput'];
    NInputNumber: typeof import('naive-ui')['NInputNumber'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    Starport: typeof import('vue-starport')['Starport'];
    StarportCarrier: typeof import('vue-starport')['StarportCarrier'];
    VApp: typeof import('vuetify/components')['VApp'];
    VAppBar: typeof import('vuetify/components')['VAppBar'];
    VAppBarNavIcon: typeof import('vuetify/components')['VAppBarNavIcon'];
    VBtn: typeof import('vuetify/components')['VBtn'];
    VCard: typeof import('vuetify/components')['VCard'];
    VInput: typeof import('vuetify/components')['VInput'];
    VMain: typeof import('vuetify/components')['VMain'];
    VNavigationDrawer: typeof import('vuetify/components')['VNavigationDrawer'];
    VTable: typeof import('vuetify/components')['VTable'];
    VTextField: typeof import('vuetify/components')['VTextField'];
    VToolbarTitle: typeof import('vuetify/components')['VToolbarTitle'];
  }
}
